C*********************************************************************
C subroutine Complete Adapted Solution Vector Derivative 2 ***********
C            -        -       -        -      -          - ***********
C Steve Gibbons Sat Feb  5 08:34:24 GMT 2000                         C
C____________________________________________________________________C
C                                                                    C
C Loops around the entire convection vector and calculates           C
C derivatives 0 and up to 2 of every harmonic from grid node         C
C IR = ILN to grid node IRN.                                         C
C                                                                    C
C____________________________________________________________________C
C                                                                    C
C Input variables :-                                                 C
C ===============                                                    C
C  Integer                                                           C
C  -------                                                           C
C                                                                    C
C     ILN       : Left-most node to be acted upon.                   C
C     IRN       : Right-most node to be acted upon.                  C
C     NBN       : Number of bounding nodes. See above.               C
C     IHD       : Highest derivative requested.                      C
C     NCFM      : Leading dimension of SVFDC. At least (2*NBN+1)     C
C     NR        : Number of radial grid nodes in each function.      C
C     NDRVS     : Number of highest derivative for which             C
C                  coefficients are stored by the array SVFDC.       C
C     NDRVM     : Limit on NDRVS. Array bound for SVFDC.             C
C     INARR     : Integer array dimension ( * ).                     C
C                  Elements may be arbitrary except for              C
C                  INARR( 1 ) = IFORMF - flag for vector format.     C
C                                        See INDFUN                  C
C                  INARR( 2 ) = NRR. Must be consistent with NR.     C
C                  INARR( 3 ) = NH = total number of radial func.s   C
C     NDCS      : Maximum distinct finite difference schemes         C
C                  stored by the array SVFDC.                        C
C     MHP       : Pointer array for harmonics. If HMP( ih ) = is     C
C                  then 'is' is the finite difference scheme used    C
C                   to take derivatives of that harm. radial func.   C
C                   If MHP is negative, the harmonic is avoided and  C
C                   CASVD2 moves on to the next harmonic.            C
C                                                                    C
C  Double Precision                                                  C
C  ----------------                                                  C
C                                                                    C
C     V         : Solution vector. Dim ( * ) but length atleast      C
C                  NR*NH.                                            C
C                                                                    C
C     SVFDC     : Finite difference coefficient matrix.              C
C                  Dimension ( NCFM, NR, NDRVM+1, NDCS ).            C
C                   Array is generated by the routine svfdcf         C
C                 See documentation for SVFDCF for details.          C
C                                                                    C
C     V0        : Zero^th derivatives. Dim ( * ) but length atleast  C
C     V1        : First   derivatives. Dim ( * ) but length atleast  C
C     V2        : Second  derivatives. Dim ( * ) but length atleast  C
C                                                                    C
C IMPORTANT: ALL of V0, V1 and V2 are filled even if                 C
C these derivatives are not requested!                               C
C                                                                    C
C____________________________________________________________________C
C
C*********************************************************************
      SUBROUTINE CASVD2 ( V, ILN, IRN, NBN, IHD, NCFM, NR, NDRVS,
     1                   NDRVM, INARR, NDCS, MHP, SVFDC, V0, V1, V2 )
      IMPLICIT NONE
C____________________________________________________________________C
C Variable declarations - Parameters ................................C
      INTEGER NBN, IHD, NCFM, NR, NDRVS, NDRVM, INARR( * ), NDCS,
     1        MHP( * ), ILN, IRN
      DOUBLE PRECISION V( * ), V0( * ), V1( * ), V2( * ),
     1                 SVFDC( NCFM, NR, NDRVM+1, NDCS )
C____________________________________________________________________C
C Variable declarations - Working variables .........................C
C
      DOUBLE PRECISION DERV( 3 )
      INTEGER IR, IH, NH, IND, INDFUN, IS, I
C____________________________________________________________________C
C START OF PROGRAM **************************************************C
C____________________________________________________________________C
C
      DO I = 1, 3
        DERV( I ) = 0.0d0
      ENDDO
C
      IF ( IHD.LT.0 .OR. IHD.GT.2 ) THEN
        PRINT *,' Subroutine CASVD2. IHD = ', IHD
        PRINT *,' Program aborted.'
        STOP
      ENDIF
C
      NH = INARR( 3 )
      DO IH = 1, NH
        IS  = MHP( IH )
        IF ( IS.LT.1 ) GOTO 60
        DO IR = ILN, IRN
C         .
          IND = INDFUN( IR, IH, INARR )
          CALL ASVDR ( V, IR, IS, IH, NBN, IHD, NCFM, NR, NDRVS,
     1                   NDRVM, DERV, INARR, SVFDC, NDCS )
C         .
          V0( IND ) = DERV( 1 )
          V1( IND ) = DERV( 2 )
          V2( IND ) = DERV( 3 )
C         .
        ENDDO
 60   CONTINUE
      ENDDO
C     .
      RETURN
      END
C*********************************************************************
