#
ALLSOURCECODE=  \
acasvd.f   cubeop.f   fopen.f    ldgnmf.f   ptdisp.f   sdrqst.f   svfrd.f     \
amccfa.f   curlqa.f   forsso.f   linerd.f   pvccf.f    sdskcv.f   svfwt.f     \
amccfo.f   cv2npl.f   forsst.f   lmfind.f   pvchgv.f   sdsmat.f   svgrth.f    \
amccft.f   cvcbta.f   forssz.f   locrbr.f   pvnsrf.f   sdsvgt.f   svkrvf.f    \
amcl.f     czpavf.f   ftaasc.f   locrnf.f   pvsfrf.f   sdsvvt.f   svlss.f     \
amdftd.f   dai2th.f   fvifta.f   locrno.f   pvtsmf.f   sdvgta.f   svnlsc.f    \
amdlt.f    dbisvf.f   fvitsr.f   loigrf.f   pvvcpl.f   sdvrvf.f   svprnt.f    \
amhsar.f   dblsvp.f   fvtgrf.f   lubmcs.f   qst2cv.f   sdvrvo.f   svrint.f    \
amhst.f    dbpisc.f   gauwts.f   magidf.f   qst2va.f   sdvrvz.f   svrqst.f    \
amlc.f     dderc3.f   gfdcfd.f   matdlt.f   qst2vf.f   secder.f   svrvfc.f    \
amlcft.f   dderc4.f   gfldcf.f   matind.f   qst2vo.f   sf2sd1.f   tdrard.f    \
amlica.f   dderc5.f   gfrdcf.f   matop.f    qsta2s.f   sf2sd2.f   tdrawt.f    \
amlp.f     dderc7.f   gno2ho.f   mc2scv.f   qsta2v.f   sf2sda.f   tftsmf.f    \
amsdea.f   dfcnrs.f   grinvo.f   mcdrhf.f   qstadf.f   sf2sdc.f   tmpmbe.f    \
amta.f     dfivto.f   grinvt.f   mcnlic.f   qstdsp.f   sf2sdd.f   tmtsmf.f    \
annlca.f   dfivts.f   grinvz.f   mcvdmf.f   qstfnd.f   sf2sdx.f   tpaqvf.f    \
anvcvt.f   dfivtz.f   gsidts.f   mdcxse.f   qt2pt.f    sf2vga.f   trapzd.f    \
anvgtt.f   dftda.f    gsldcf.f   mfdmfm.f   quadop.f   sf2vgb.f   tsbrva.f    \
asfgr.f    dfvdmf.f   gsrdcf.f   mfdrhf.f   radvlf.f   sf2vgc.f   tsbrvf.f    \
asrqst.f   djvhmf.f   hmfrd.f    mfgeps.f   rccvva.f   sf2vgd.f   tsidts.f    \
assvar.f   dl.f       hmfwt.f    mfhmsr.f   rckcva.f   sf2vgt.f   tsigrf.f    \
asv2vf.f   dldl.f     hminda.f   mfseps.f   rcldr.f    sf2vgx.f   tvsfrf.f    \
asvccf.f   dm2e.f     hmtac.f    mhdbcs.f   rcldr2.f   sfafil.f   tvtsmf.f    \
asvcl.f    dmlgci.f   ho2gno.f   mmaxfd.f   rcmata.f   sfcshc.f   ugmbce.f    \
asvcp.f    dmwmf.f    htmrbe.f   mnewtr.f   rcvgia.f   sfddm2.f   ugmica.f    \
asvcpl.f   dpa2i2.f   ibtdva.f   mspavf.f   rcvgta.f   sfddmf.f   v2nplt.f    \
asvdr.f    dpa2if.f   ienlt2.f   newtrs.f   rmatop.f   sfoxse.f   v2qsta.f    \
asvhst.f   dplm.f     ienltf.f   ngmbce.f   rmccfa.f   sfseti.f   vachgv.f    \
asvita.f   dpmbce.f   ienlto.f   ngmcl.f    rqsrvf.f   sh2qst.f   vccpcc.f    \
asvitl.f   dpmbta.f   iiasce.f   ngmica.f   rqsrvo.f   shc2pt.f   vccpcg.f    \
asvlc.f    dpmbvf.f   imfmbe.f   ngmlc.f    rqsrvz.f   shcanc.f   vcpcc.f     \
asvlp.f    dpmcmf.f   imfrbe.f   ngmlp.f    rqstca.f   shccvf.f   vdgrta.f    \
asvrvf.f   dpmcta.f   indfun.f   ngmta.f    rqstcf.f   shcfnd.f   vdgtts.f    \
asvta.f    dpmdft.f   indshc.f   ngsvcl.f   rqstcl.f   shdplg.f   vec2ds.f    \
av0cva.f   dpmes.f    innlca.f   ngsvdr.f   rqstco.f   shell1.f   veccp.f     \
av0gta.f   dpml1a.f   intcfd.f   ngsvlc.f   rqstcp.f   shkeer.f   vecdsp.f    \
avbmbr.f   dpml2a.f   intfrd.f   ngsvlp.f   rqstdo.f   shmplg.f   vecfil.f    \
avcv0a.f   dpml3a.f   invcvt.f   ngsvta.f   rqstdp.f   shnkcv.f   vecop.f     \
avdgta.f   dpmm.f     invgit.f   nivtso.f   rqstdr.f   shnmat.f   velmbe.f    \
avgt0a.f   dpmm1.f    invgtt.f   nivtsr.f   rqstof.f   shnvgi.f   velrbe.f    \
avmata.f   dpmsta.f   invmft.f   nivtsz.f   rqstso.f   shnvgt.f   vesr.f      \
avmato.f   dpmtda.f   invsso.f   nlits.f    rqstsv.f   shnvvt.f   vf2qsa.f    \
avmlta.f   dpmv0t.f   invsst.f   nmcxse.f   rqstvf.f   shoder.f   vf2qso.f    \
avmlto.f   dpmv0v.f   iocrbd.f   nmlica.f   rsdv2a.f   shsel.f    vf2qst.f    \
avvlta.f   dpmvgt.f   iocrbo.f   nntppf.f   rsdv2b.f   shsfrd.f   vf2sdv.f    \
bihfrd.f   dpmvt0.f   iocrbr.f   nntppz.f   rsdv2c.f   shsfwt.f   vfafil.f    \
binitf.f   dpmvv.f    iocrbt.f   npfvcr.f   rsdv2d.f   shvecf.f   vfcor.f     \
blcnrs.f   dpmvv0.f   ishcia.f   nphpf.f    rsdv2e.f   shveco.f   vfcp.f      \
bma2bm.f   dpvbce.f   itfa.f     npinfw.f   rsdv2r.f   shvect.f   vfdp.f      \
bmrcop.f   dpvbta.f   itfcf.f    nplifw.f   rsdv2x.f   sicrbd.f   vfesdv.f    \
bmscd.f    dpvcta.f   ithcar.f   npudfs.f   rsdver.f   sicrbi.f   vfrqst.f    \
bmsmsl.f   dpvdft.f   itmrbe.f   nrcwmf.f   rtpfce.f   sicrbo.f   vfscex.f    \
bmwdfs.f   dpvl1a.f   itslsr.f   nsdsdr.f   rv0cva.f   sicrbr.f   vfscge.f    \
bmwdsl.f   dpvl2a.f   itvaaf.f   nsidto.f   rv0gta.f   sicrbs.f   vgptpf.f    \
casvd2.f   dpvl3a.f   itvvaf.f   nsidts.f   rv0mfa.f   sicrbt.f   vicexr.f    \
casvdr.f   dpvpaf.f   iv0cva.f   nsidtz.f   rvcv0a.f   simcts.f   vlicer.f    \
ccvspe.f   dpvrvf.f   iv0cvo.f   nsvbta.f   rvfcf.f    simfts.f   vmeps.f     \
cdcbkr.f   dpvsta.f   iv0gta.f   nsvhst.f   rvfcf2.f   smitsl.f   vobmar.f    \
cdpkrf.f   dpvtda.f   iv0gto.f   ntsvfo.f   rvfcit.f   sqrll1.f   vobmb2.f    \
ce1krf.f   dpvvta.f   ivcv0a.f   ntsvft.f   rvfcp.f    srcvva.f   vobmbr.f    \
cendif.f   dpvvva.f   ivcv0o.f   ntsvfz.f   rvfcp2.f   srkcva.f   vohmsr.f    \
cfvicc.f   dvecz.f    ivgt0a.f   numint.f   rvfcpo.f   srmata.f   vspcc.f     \
chindf.f   e2dm.f     ivgt0o.f   oddevn.f   rvfdvf.f   srvgta.f   vtfhsr.f    \
chorcf.f   earcmc.f   ivicts.f   ofifr.f    rvfdvo.f   ssvcl.f    vthmsr.f    \
chorch.f   earmir.f   ivsits.f   ofrqst.f   rvfrqo.f   ssvfta.f   xarrcc.f    \
chorsf.f   ebmvm.f    jvkeif.f   ofvfr.f    rvfrqs.f   ssvhst.f   xarrrd.f    \
chrsef.f   emmult.f   kdcmrn.f   ontppf.f   rvfrqz.f   ssvlc.f    xarrwt.f    \
cicdts.f   esnaas.f   kdiet2.f   pf2sof.f   rvgi0a.f   ssvlp.f    xsvcbe.f    \
cindsw.f   espavf.f   kdieto.f   pflscg.f   rvgt0a.f   ssvta.f    xsvsci.f    \
cntric.f   evalas.f   kdiets.f   pftsmf.f   rvmlta.f   stcift.f   xsvsda.f    \
cochgv.f   evecex.f   kdthsr.f   plm.f      rvvgta.f   strts.f    xsvsdb.f    \
coefrd.f   exforc.f   klm.f      pmfabf.f   rvvgto.f   stsvft.f   xsvsdc.f    \
corcof.f   extfin.f   krvhmf.f   pmfgfr.f   rvvgtz.f   sv2qa.f    xsvsdd.f    \
corcoo.f   fclose.f   lapslv.f   pmfirf.f   sbcs2n.f   sv2qst.f   xsvsde.f    \
corts.f    fdcdsp.f   lapts.f    pmfsef.f   sbmvmr.f   sv2shc.f   xsvsdv.f    \
cpcovr.f   fdcinv.f   lcfmta.f   pmm.f      sbrcts.f   sv2xsa.f   zcpaa2.f    \
crfeic.f   fdcmbd.f   lcftsm.f   pmm1.f     sbrrfc.f   sv2xso.f   zcpaas.f    \
crfeif.f   fftnew.f   lcgrcc.f   potfer.f   sbrvmr.f   svderf.f   zvdf.f      \
crfetr.f   fftrlv.f   lcrhsf.f   powtwo.f   schnla.f   svdjvf.f   zvnff.f     \
crtpfe.f   fnamer.f   lcsits.f   psigrf.f   sdrqso.f   svfdcf.f   xsvsdf.f    \
xarrc2.f   rsdv2f.f
#
BLSCNLSC_SOURCES= \
   vecop.f fopen.f fclose.f esnaas.f zcpaas.f ontppf.f    \
   gauwts.f schnla.f vthmsr.f cindsw.f svfdcf.f fdcmbd.f  \
   shcanc.f ithcar.f blcnrs.f hmfwt.f svfwt.f xarrwt.f    \
   itfa.f  svprnt.f fnamer.f ldgnmf.f gfdcfd.f lmfind.f   \
   itfcf.f cntric.f vspcc.f vccpcc.f casvdr.f ibtdva.f    \
   ssvlc.f ssvlp.f ssvhst.f ssvta.f sdrqst.f sdvgta.f     \
   rqstcf.f rqstcp.f rqstca.f rqstsv.f avmlta.f rv0cva.f  \
   rvcv0a.f rv0gta.f rvgi0a.f amsdea.f nrcwmf.f bmwdfs.f  \
   asvcpl.f radvlf.f matop.f shvect.f vfdp.f  forsst.f    \
   vfcp.f  vf2qst.f asvdr.f rqstvf.f grinvt.f vfcor.f     \
   vfrqst.f rqstdr.f amlp.f  amlc.f  amccfa.f amta.f      \
   amcl.f  amhst.f invcvt.f vicexr.f innlca.f invgtt.f    \
   invgit.f bmrcop.f cubeop.f fftrlv.f dvecz.f amdlt.f    \
   amlica.f amccft.f corcof.f amhsar.f matind.f powtwo.f  \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   emmult.f dl.f    dldl.f  sqrll1.f indfun.f indshc.f
#
BLSCNLSIC_SOURCES= \
   fopen.f vecop.f esnaas.f zcpaas.f ontppf.f gauwts.f    \
   schnla.f vthmsr.f cindsw.f svfdcf.f fdcmbd.f shcanc.f  \
   ithcar.f blcnrs.f shkeer.f hmfwt.f svfwt.f xarrwt.f    \
   svprnt.f vtfhsr.f itslsr.f fclose.f fnamer.f ldgnmf.f  \
   gfdcfd.f lmfind.f itfcf.f cntric.f vspcc.f vccpcc.f    \
   casvdr.f ibtdva.f ssvlc.f ssvlp.f ssvhst.f ssvta.f     \
   sdrqst.f sdvgta.f rqstcf.f rqstcp.f rqstca.f rqstsv.f  \
   avmlta.f rv0cva.f rvcv0a.f rv0gta.f rvgi0a.f amsdea.f  \
   nrcwmf.f bmwdfs.f asvcpl.f asvdr.f radvlf.f sbrrfc.f   \
   vmeps.f evalas.f evecex.f matop.f shvect.f vfdp.f      \
   forsst.f vfcp.f  vf2qst.f itfa.f  rqstvf.f grinvt.f    \
   vfcor.f vfrqst.f rqstdr.f amlp.f  amlc.f  amccfa.f     \
   amta.f  amcl.f  amhst.f invcvt.f vicexr.f innlca.f     \
   invgtt.f invgit.f bmrcop.f dvecz.f asvta.f asvcl.f     \
   vesr.f  cubeop.f fftrlv.f amdlt.f amlica.f amccft.f    \
   corcof.f amhsar.f matind.f powtwo.f pmm.f   pmm1.f     \
   plm.f   dpmm.f  dpmm1.f dplm.f  emmult.f sqrll1.f      \
   dl.f    dldl.f  indshc.f indfun.f
#
BLSCNLSIC_EVECS_SOURCES= \
   fopen.f vecop.f esnaas.f zcpaas.f ontppf.f gauwts.f    \
   schnla.f vthmsr.f cindsw.f svfdcf.f fdcmbd.f shcanc.f  \
   ithcar.f blcnrs.f shkeer.f hmfwt.f svfwt.f xarrwt.f    \
   svprnt.f vtfhsr.f itslsr.f evecex.f fclose.f fnamer.f  \
   ldgnmf.f gfdcfd.f lmfind.f itfcf.f cntric.f vspcc.f    \
   vccpcc.f casvdr.f ibtdva.f ssvlc.f ssvlp.f ssvhst.f    \
   ssvta.f sdrqst.f sdvgta.f rqstcf.f rqstcp.f rqstca.f   \
   rqstsv.f avmlta.f rv0cva.f rvcv0a.f rv0gta.f rvgi0a.f  \
   amsdea.f nrcwmf.f bmwdfs.f asvcpl.f asvdr.f radvlf.f   \
   sbrrfc.f vmeps.f evalas.f matop.f shvect.f vfdp.f      \
   forsst.f vfcp.f  vf2qst.f itfa.f  rqstvf.f grinvt.f    \
   vfcor.f vfrqst.f rqstdr.f amlp.f  amlc.f  amccfa.f     \
   amta.f  amcl.f  amhst.f invcvt.f vicexr.f innlca.f     \
   invgtt.f invgit.f bmrcop.f dvecz.f asvta.f asvcl.f     \
   vesr.f  cubeop.f fftrlv.f amdlt.f amlica.f amccft.f    \
   corcof.f amhsar.f matind.f powtwo.f pmm.f   pmm1.f     \
   plm.f   dpmm.f  dpmm1.f dplm.f  emmult.f sqrll1.f      \
   dl.f    dldl.f  indshc.f indfun.f
#
CICIBCDTS2_SOURCES= \
   fopen.f shkeer.f hmfrd.f svfrd.f xarrrd.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f    \
   schnla.f pvtsmf.f tvtsmf.f tmtsmf.f pftsmf.f tftsmf.f  \
   avbmbr.f vobmbr.f xarrcc.f asvcpl.f svfwt.f pvvcpl.f   \
   vecop.f nsvhst.f nsvbta.f rsdv2c.f sf2vgc.f sf2sdc.f   \
   xsvsdc.f rsdv2d.f rsdv2e.f sf2vgd.f sf2sdd.f xsvsdd.f  \
   xsvsde.f mdcxse.f fclose.f bihfrd.f itvaaf.f fnamer.f  \
   asvdr.f ldgnmf.f gfdcfd.f matop.f amlica.f amsdea.f    \
   amdlt.f vobmar.f nmlica.f dvecz.f fftrlv.f svrint.f    \
   matind.f bmrcop.f powtwo.f sqrll1.f emmult.f pmm.f     \
   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f  dl.f           \
   indfun.f
#
CICM2OCDISPLAY_SOURCES= \
   hmfwt.f svfwt.f xarrc2.f xarrrd.f bihfrd.f indfun.f    \
   fopen.f svfrd.f xarrwt.f svrint.f fclose.f fnamer.f    \
   gfdcfd.f matop.f
#
CICMIBCDTS2_SOURCES= \
   fopen.f shkeer.f hmfrd.f svfrd.f xarrrd.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f    \
   schnla.f pvtsmf.f tvtsmf.f tmtsmf.f pftsmf.f tftsmf.f  \
   avbmbr.f vobmbr.f xarrc2.f asvcpl.f svfwt.f pvvcpl.f   \
   vecop.f nsvhst.f nsvbta.f rsdv2c.f sf2vgc.f sf2sdc.f   \
   xsvsdc.f rsdv2d.f rsdv2f.f sf2vgd.f sf2sdd.f xsvsdd.f  \
   xsvsdf.f mdcxse.f fclose.f bihfrd.f itvaaf.f fnamer.f  \
   asvdr.f ldgnmf.f gfdcfd.f matop.f amlica.f amsdea.f    \
   amdlt.f vobmar.f nmlica.f dvecz.f fftrlv.f svrint.f    \
   matind.f bmrcop.f powtwo.f sqrll1.f emmult.f pmm.f     \
   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f  dl.f           \
   indfun.f
#
CICMSVPNSMAP_SOURCES= \
   hmfrd.f svfrd.f xarrrd.f hminda.f esnaas.f zcpaas.f    \
   zcpaa2.f svrint.f hmfwt.f xarrwt.f svfwt.f fopen.f     \
   fclose.f gfdcfd.f fnamer.f matop.f indfun.f
#
CICMUBCDTS2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f xarrc2.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f shkeer.f nphpf.f    \
   gauwts.f schnla.f pvtsmf.f tvtsmf.f tmtsmf.f pftsmf.f  \
   tftsmf.f avbmbr.f vobmbr.f rsdv2c.f sf2vgc.f sf2sdc.f  \
   xsvsdc.f asvcpl.f svfwt.f fclose.f pvvcpl.f vecop.f    \
   nsvhst.f nsvbta.f sf2vgd.f rsdv2d.f rsdv2f.f mdcxse.f  \
   sf2sdd.f xsvsdd.f xsvsdf.f fnamer.f ldgnmf.f gfdcfd.f  \
   asvdr.f svrint.f matop.f amlica.f amsdea.f amdlt.f     \
   vobmar.f nmlica.f dvecz.f fftrlv.f matind.f bmrcop.f   \
   powtwo.f rtpfce.f emmult.f sqrll1.f shmplg.f shdplg.f  \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   indfun.f
#
CICSVPNSMAP_SOURCES= \
   hmfrd.f svfrd.f xarrrd.f hminda.f esnaas.f zcpaas.f    \
   zcpaa2.f svrint.f hmfwt.f xarrwt.f svfwt.f fopen.f     \
   fclose.f gfdcfd.f fnamer.f matop.f indfun.f
#
CICUBCDTS2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f xarrcc.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f shkeer.f nphpf.f    \
   gauwts.f schnla.f pvtsmf.f tvtsmf.f tmtsmf.f pftsmf.f  \
   tftsmf.f avbmbr.f vobmbr.f rsdv2c.f sf2vgc.f sf2sdc.f  \
   xsvsdc.f asvcpl.f svfwt.f fclose.f pvvcpl.f vecop.f    \
   nsvhst.f nsvbta.f sf2vgd.f rsdv2d.f rsdv2e.f mdcxse.f  \
   sf2sdd.f xsvsdd.f xsvsde.f fnamer.f ldgnmf.f gfdcfd.f  \
   asvdr.f svrint.f matop.f amlica.f amsdea.f amdlt.f     \
   vobmar.f nmlica.f dvecz.f fftrlv.f matind.f bmrcop.f   \
   powtwo.f rtpfce.f emmult.f sqrll1.f shmplg.f shdplg.f  \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   indfun.f
#
DJIEPGRF_SOURCES= \
   fopen.f djvhmf.f esnaas.f zcpaas.f svdjvf.f kdthsr.f   \
   svfdcf.f ontppf.f gauwts.f schnla.f matop.f vcpcc.f    \
   rv0mfa.f amlp.f  mfseps.f hmfwt.f xarrwt.f evecex.f    \
   svfwt.f fclose.f fnamer.f cntric.f ldgnmf.f gfdcfd.f   \
   shvect.f vfcp.f  vf2qst.f invmft.f vicexr.f innlca.f   \
   amdlt.f amlica.f amta.f  amsdea.f vecop.f asvta.f      \
   asvcpl.f cubeop.f dvecz.f fftrlv.f asvdr.f matind.f    \
   bmrcop.f powtwo.f emmult.f pmm.f   pmm1.f  plm.f       \
   dpmm.f  dpmm1.f dplm.f  sqrll1.f indfun.f indshc.f
#
IIC2CICSC_SOURCES= \
   vecop.f hmfrd.f svfrd.f xarrrd.f esnaas.f zcpaas.f     \
   zcpaa2.f hmfwt.f xarrwt.f svfwt.f fopen.f fclose.f     \
   fnamer.f indfun.f
#
ITFVF_SOURCES= \
   vecop.f fopen.f fclose.f esnaas.f zcpaas.f shcanc.f    \
   ithcar.f itfa.f hmfwt.f svfwt.f xarrwt.f fnamer.f      \
   lmfind.f itfcf.f cntric.f indfun.f indshc.f
#
KRCMRNIF_SOURCES= \
   fopen.f krvhmf.f esnaas.f zcpaas.f svkrvf.f kdthsr.f   \
   svfdcf.f ontppf.f gauwts.f schnla.f kdcmrn.f hmfwt.f   \
   xarrwt.f svfwt.f fclose.f fnamer.f radvlf.f cntric.f   \
   ldgnmf.f gfdcfd.f vcpcc.f matop.f rv0mfa.f amlp.f      \
   mfseps.f evecex.f shvect.f vfcp.f  vf2qst.f invmft.f   \
   vicexr.f innlca.f amdlt.f amlica.f amta.f  amsdea.f    \
   vecop.f asvta.f asvcpl.f cubeop.f dvecz.f fftrlv.f     \
   asvdr.f matind.f bmrcop.f powtwo.f emmult.f pmm.f      \
   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f  sqrll1.f       \
   indfun.f indshc.f
#
KRDDMCMRNIF_SOURCES= \
   fopen.f krvhmf.f esnaas.f zcpaas.f svkrvf.f kdthsr.f   \
   svfdcf.f ontppf.f gauwts.f schnla.f dm2e.f  kdcmrn.f   \
   hmfwt.f xarrwt.f svfwt.f fclose.f fnamer.f radvlf.f    \
   cntric.f ldgnmf.f gfdcfd.f vcpcc.f matop.f rv0mfa.f    \
   amlp.f  mfseps.f evecex.f shvect.f vfcp.f  vf2qst.f    \
   invmft.f vicexr.f innlca.f amdlt.f amlica.f amta.f     \
   amsdea.f vecop.f asvta.f asvcpl.f cubeop.f dvecz.f     \
   fftrlv.f asvdr.f matind.f bmrcop.f powtwo.f emmult.f   \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   sqrll1.f indfun.f indshc.f
#
KRIEPGRF_SOURCES= \
   fopen.f krvhmf.f esnaas.f zcpaas.f svkrvf.f kdthsr.f   \
   svfdcf.f ontppf.f gauwts.f schnla.f matop.f vcpcc.f    \
   rv0mfa.f amlp.f  mfseps.f hmfwt.f xarrwt.f evecex.f    \
   svfwt.f fclose.f fnamer.f radvlf.f cntric.f ldgnmf.f   \
   gfdcfd.f shvect.f vfcp.f  vf2qst.f invmft.f vicexr.f   \
   innlca.f amdlt.f amlica.f amta.f  amsdea.f vecop.f     \
   asvta.f asvcpl.f cubeop.f dvecz.f fftrlv.f asvdr.f     \
   matind.f bmrcop.f powtwo.f emmult.f pmm.f   pmm1.f     \
   plm.f   dpmm.f  dpmm1.f dplm.f  sqrll1.f indfun.f      \
   indshc.f
#
KRSSGEPS_SOURCES= \
   fopen.f krvhmf.f esnaas.f zcpaas.f svkrvf.f kdthsr.f   \
   svfdcf.f ontppf.f gauwts.f schnla.f matop.f vcpcc.f    \
   rv0mfa.f mfgeps.f hmfwt.f xarrwt.f evecex.f svfwt.f    \
   fclose.f fnamer.f radvlf.f cntric.f ldgnmf.f gfdcfd.f  \
   shvect.f vfcp.f  vf2qst.f invmft.f vicexr.f innlca.f   \
   amlp.f  amsdea.f vecop.f asvlp.f asvcpl.f cubeop.f     \
   dvecz.f fftrlv.f asvdr.f matind.f amdlt.f amlica.f     \
   bmrcop.f powtwo.f emmult.f pmm.f   pmm1.f  plm.f       \
   dpmm.f  dpmm1.f dplm.f  sqrll1.f dl.f    indfun.f      \
   indshc.f
#
LEEPV1_SOURCES= \
   esnaas.f svfdcf.f lcfmta.f mfseps.f evecex.f svfwt.f   \
   fopen.f fclose.f xarrwt.f ldgnmf.f gfdcfd.f matop.f    \
   amlica.f amlcft.f amta.f  amsdea.f vecop.f asvta.f     \
   asvcpl.f fnamer.f matind.f amdlt.f bmrcop.f asvdr.f    \
   emmult.f indfun.f
#
LETSV1_SOURCES= \
   xarrrd.f svfrd.f svfdcf.f lcftsm.f lcsits.f veccp.f    \
   svfwt.f fopen.f fclose.f ldgnmf.f gfdcfd.f matop.f     \
   amlica.f amlcft.f amdlt.f amsdea.f vecop.f lcrhsf.f    \
   asvcpl.f fnamer.f matind.f bmrcop.f asvdr.f emmult.f   \
   indfun.f
#
LINONS1_SOURCES= \
   fopen.f esnaas.f zcpaas.f ontppf.f gauwts.f schnla.f   \
   vthmsr.f cindsw.f svfdcf.f locrnf.f hmfwt.f svfwt.f    \
   xarrwt.f svprnt.f fclose.f fnamer.f ldgnmf.f gfdcfd.f  \
   avmlta.f sbrrfc.f vmeps.f evalas.f evecex.f radvlf.f   \
   matop.f amlp.f  amlc.f  amccfa.f amta.f  amcl.f        \
   amhst.f vecop.f bmrcop.f amsdea.f dvecz.f asvta.f      \
   asvcl.f vesr.f  asvcpl.f amdlt.f amlica.f amccft.f     \
   corcof.f amhsar.f asvdr.f matind.f shvect.f vfcor.f    \
   vf2qst.f cubeop.f fftrlv.f powtwo.f pmm.f   pmm1.f     \
   plm.f   dpmm.f  dpmm1.f dplm.f  emmult.f dl.f          \
   sqrll1.f indfun.f indshc.f
#
LINONS2_SOURCES= \
   fopen.f esnaas.f zcpaas.f ontppf.f gauwts.f schnla.f   \
   vthmsr.f cindsw.f svfdcf.f locrbr.f hmfwt.f svfwt.f    \
   xarrwt.f svprnt.f fclose.f fnamer.f ldgnmf.f gfdcfd.f  \
   avmlta.f sbrrfc.f vmeps.f evalas.f evecex.f radvlf.f   \
   matop.f amlp.f  amlc.f  amccfa.f amta.f  amcl.f        \
   amhst.f vecop.f bmrcop.f amsdea.f dvecz.f asvta.f      \
   asvcl.f vesr.f  asvcpl.f amdlt.f amlica.f amccft.f     \
   corcof.f amhsar.f asvdr.f matind.f shvect.f vfcor.f    \
   vf2qst.f cubeop.f fftrlv.f powtwo.f                    \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   emmult.f dl.f    sqrll1.f indfun.f indshc.f
#
MFCANAL1_SOURCES= \
   hmfrd.f svfrd.f xarrrd.f fopen.f svfdcf.f ontppf.f     \
   gauwts.f schnla.f casvd2.f shkeer.f sv2xsa.f xsvsci.f  \
   fclose.f fnamer.f ldgnmf.f gfdcfd.f asvdr.f vecop.f    \
   fftrlv.f matop.f powtwo.f emmult.f pmm.f   pmm1.f      \
   plm.f   dpmm.f  dpmm1.f dplm.f  sqrll1.f indfun.f
#
MSVIP_SOURCES= \
   esnaas.f zcpaas.f hminda.f shvecf.f bihfrd.f svfrd.f   \
   xarrrd.f assvar.f hmfwt.f svfwt.f xarrwt.f fopen.f     \
   fclose.f svrint.f smitsl.f pmfabf.f fnamer.f gfdcfd.f  \
   mnewtr.f matop.f pvnsrf.f tvsfrf.f pvsfrf.f pmfirf.f   \
   chorch.f chorcf.f chorsf.f pmfsef.f indfun.f
#
NWSVPNSMAP_SOURCES= \
   hmfrd.f svfrd.f xarrrd.f hminda.f esnaas.f zcpaas.f    \
   svrint.f hmfwt.f xarrwt.f svfwt.f fopen.f fclose.f     \
   gfdcfd.f fnamer.f matop.f indfun.f
#
OLD2NEW_MF_SOURCES= \
   ofifr.f ofvfr.f esnaas.f xarrwt.f svfwt.f hmfwt.f      \
   fopen.f cntric.f fclose.f fnamer.f indfun.f
#
O2DFITFSOC2_SOURCES= \
   fopen.f linerd.f hmfrd.f svfrd.f bihfrd.f xarrrd.f     \
   svfdcf.f fdcmbd.f iiasce.f shkeer.f mc2scv.f pvccf.f   \
   nphpf.f gauwts.f schnla.f itvvaf.f pvtsmf.f tvtsmf.f   \
   avbmbr.f vobmbr.f asvcpl.f svrint.f svfwt.f pvvcpl.f   \
   vecop.f rsdv2c.f rsdv2d.f sfoxse.f xsvsdc.f xsvsdd.f   \
   fclose.f fnamer.f ldgnmf.f gfdcfd.f asvdr.f matop.f    \
   amlica.f amsdea.f amdlt.f vobmar.f nmlica.f dvecz.f    \
   fftrlv.f matind.f bmrcop.f powtwo.f emmult.f sqrll1.f  \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   indfun.f
#
O2DFITFSOC2SBR_SOURCES= \
   fopen.f tsbrvf.f tsbrva.f linerd.f hmfrd.f svfrd.f     \
   bihfrd.f xarrrd.f svfdcf.f fdcmbd.f iiasce.f shkeer.f  \
   mc2scv.f pvccf.f nphpf.f gauwts.f schnla.f itvvaf.f    \
   pvtsmf.f tvtsmf.f avbmbr.f vobmbr.f asvcpl.f svrint.f  \
   svfwt.f pvvcpl.f vecop.f rsdv2c.f rsdv2d.f sfoxse.f    \
   xsvsdc.f xsvsdd.f fclose.f fnamer.f ldgnmf.f gfdcfd.f  \
   asvdr.f matop.f amlica.f amsdea.f amdlt.f vobmar.f     \
   nmlica.f dvecz.f fftrlv.f matind.f bmrcop.f powtwo.f   \
   emmult.f sqrll1.f pmm.f   pmm1.f  plm.f   dpmm.f       \
   dpmm1.f dplm.f  indfun.f
#
O2DFITFTC2_SOURCES= \
   fopen.f hmfrd.f svfrd.f bihfrd.f shkeer.f xarrrd.f     \
   linerd.f svfdcf.f fdcmbd.f iiasce.f mc2scv.f pvccf.f   \
   nphpf.f gauwts.f schnla.f itvvaf.f pvtsmf.f tvtsmf.f   \
   tmtsmf.f avbmbr.f vobmbr.f asvcpl.f svrint.f svfwt.f   \
   pvvcpl.f vecop.f nsvhst.f nsvbta.f rsdv2c.f rsdv2d.f   \
   sf2vgc.f sf2vgd.f nmcxse.f sf2sdc.f sf2sdd.f xsvsdc.f  \
   xsvsdd.f fclose.f fnamer.f asvdr.f ldgnmf.f gfdcfd.f   \
   matop.f amlica.f amsdea.f amdlt.f vobmar.f nmlica.f    \
   dvecz.f fftrlv.f matind.f bmrcop.f powtwo.f sqrll1.f   \
   emmult.f pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f       \
   dplm.f  indfun.f
#
O2DFITFTC2SBR_SOURCES= \
   fopen.f hmfrd.f svfrd.f bihfrd.f shkeer.f xarrrd.f     \
   linerd.f svfdcf.f fdcmbd.f iiasce.f mc2scv.f pvccf.f   \
   nphpf.f gauwts.f schnla.f itvvaf.f pvtsmf.f tvtsmf.f   \
   tmtsmf.f avbmbr.f vobmbr.f asvcpl.f svrint.f svfwt.f   \
   pvvcpl.f vecop.f nsvhst.f nsvbta.f rsdv2c.f rsdv2d.f   \
   sf2vgc.f sf2vgd.f nmcxse.f sf2sdc.f sf2sdd.f xsvsdc.f  \
   xsvsdd.f fclose.f tsbrva.f fnamer.f asvdr.f ldgnmf.f   \
   gfdcfd.f matop.f amlica.f amsdea.f amdlt.f vobmar.f    \
   nmlica.f dvecz.f fftrlv.f matind.f bmrcop.f powtwo.f   \
   sqrll1.f emmult.f pmm.f   pmm1.f  plm.f   dpmm.f       \
   dpmm1.f dplm.f  indfun.f
#
O2IBCDTS2_SOURCES= \
   fopen.f shkeer.f hmfrd.f svfrd.f xarrrd.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f    \
   schnla.f pvtsmf.f tvtsmf.f tmtsmf.f pftsmf.f tftsmf.f  \
   avbmbr.f vobmbr.f asvcpl.f svfwt.f pvvcpl.f vecop.f    \
   nsvhst.f nsvbta.f rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f  \
   rsdv2d.f sf2vgd.f sf2sdd.f xsvsdd.f mdcxse.f fclose.f  \
   bihfrd.f itvaaf.f fnamer.f asvdr.f ldgnmf.f gfdcfd.f   \
   matop.f amlica.f amsdea.f amdlt.f vobmar.f nmlica.f    \
   dvecz.f fftrlv.f svrint.f matind.f bmrcop.f powtwo.f   \
   sqrll1.f emmult.f pmm.f   pmm1.f  plm.f   dpmm.f       \
   dpmm1.f dplm.f  dl.f    indfun.f
#
O2IBTCTSC2_SOURCES= \
   fopen.f shkeer.f hmfrd.f svfrd.f xarrrd.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f    \
   schnla.f pvtsmf.f tvtsmf.f tmtsmf.f avbmbr.f vobmbr.f  \
   asvcpl.f svfwt.f pvvcpl.f vecop.f nsvhst.f nsvbta.f    \
   rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f rsdv2d.f sf2vgd.f  \
   sf2sdd.f xsvsdd.f nmcxse.f fclose.f bihfrd.f itvaaf.f  \
   fnamer.f asvdr.f ldgnmf.f gfdcfd.f matop.f amlica.f    \
   amsdea.f amdlt.f vobmar.f nmlica.f dvecz.f fftrlv.f    \
   svrint.f matind.f bmrcop.f powtwo.f sqrll1.f emmult.f  \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   dl.f    indfun.f
#
O2IBTCTSC3_SOURCES= \
   fopen.f shkeer.f hmfrd.f svfrd.f xarrrd.f svfdcf.f     \
   fdcmbd.f iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f    \
   schnla.f pvtsmf.f tvtsmf.f tmtsmf.f avbmbr.f vobmbr.f  \
   asvcpl.f svfwt.f pvvcpl.f vecop.f nsvhst.f nsvbta.f    \
   rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f rsdv2d.f sf2vgd.f  \
   sf2sdd.f xsvsdd.f nmcxse.f fclose.f bihfrd.f itvaaf.f  \
   svrint.f fnamer.f asvdr.f ldgnmf.f gfdcfd.f matop.f    \
   amlica.f amsdea.f amdlt.f vobmar.f nmlica.f dvecz.f    \
   fftrlv.f matind.f bmrcop.f powtwo.f rtpfce.f shmplg.f  \
   shdplg.f sqrll1.f emmult.f pmm.f   pmm1.f  plm.f       \
   dpmm.f  dpmm1.f dplm.f  dl.f    indfun.f
#
O2UBCDTS2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f svfdcf.f fdcmbd.f     \
   iiasce.f mc2scv.f pvccf.f shkeer.f nphpf.f gauwts.f    \
   schnla.f pvtsmf.f tvtsmf.f tmtsmf.f pftsmf.f tftsmf.f  \
   avbmbr.f vobmbr.f rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f  \
   asvcpl.f svfwt.f fclose.f pvvcpl.f vecop.f nsvhst.f    \
   nsvbta.f rsdv2d.f sf2vgd.f mdcxse.f sf2sdd.f xsvsdd.f  \
   fnamer.f ldgnmf.f gfdcfd.f asvdr.f svrint.f matop.f    \
   amlica.f amsdea.f amdlt.f vobmar.f nmlica.f dvecz.f    \
   fftrlv.f matind.f bmrcop.f powtwo.f rtpfce.f emmult.f  \
   sqrll1.f shmplg.f shdplg.f pmm.f pmm1.f plm.f          \
   dpmm.f dpmm1.f dplm.f indfun.f
#
O2UBTCTSC2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f svfdcf.f fdcmbd.f     \
   iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f schnla.f    \
   pvtsmf.f tvtsmf.f tmtsmf.f avbmbr.f vobmbr.f asvcpl.f  \
   svfwt.f pvvcpl.f vecop.f nsvhst.f nsvbta.f rsdv2c.f    \
   sf2vgc.f sf2sdc.f xsvsdc.f rsdv2d.f sf2vgd.f sf2sdd.f  \
   xsvsdd.f nmcxse.f fclose.f shkeer.f fnamer.f ldgnmf.f  \
   gfdcfd.f matop.f amlica.f amsdea.f amdlt.f vobmar.f    \
   nmlica.f asvdr.f dvecz.f fftrlv.f svrint.f matind.f    \
   bmrcop.f powtwo.f rtpfce.f emmult.f pmm.f   pmm1.f     \
   plm.f   dpmm.f  dpmm1.f dplm.f  shmplg.f shdplg.f      \
   sqrll1.f indfun.f
#
PAR_CICMIBCDTS2_SOURCES= \
   sf2sdc.f fdcmbd.f xarrrd.f svfwt.f shkeer.f nsvhst.f   \
   schnla.f bihfrd.f avbmbr.f xarrc2.f vecop.f rsdv2c.f   \
   nphpf.f xsvsdc.f gauwts.f fopen.f iiasce.f vobmb2.f    \
   hmfrd.f svfrd.f nsvbta.f asvcpl.f dvecz.f fclose.f     \
   pvvcpl.f svfdcf.f mc2scv.f sf2vgc.f pvccf.f dplm.f     \
   pmm.f   fnamer.f dl.f    emmult.f dpmm.f  vobmar.f     \
   indfun.f asvdr.f amsdea.f gfdcfd.f matop.f amlica.f    \
   pmm1.f  amdlt.f svrint.f fftrlv.f nmlica.f dpmm1.f     \
   plm.f   ldgnmf.f sqrll1.f matind.f bmrcop.f
#
PAR_CICMUBCDTS2_SOURCES= \
   matind.f bmrcop.f sf2sdc.f fdcmbd.f xarrrd.f svfwt.f   \
   shkeer.f nsvhst.f schnla.f avbmbr.f xarrc2.f vecop.f   \
   rsdv2c.f nphpf.f xsvsdc.f gauwts.f fopen.f rtpfce.f    \
   iiasce.f vobmb2.f hmfrd.f svfrd.f nsvbta.f asvcpl.f    \
   dvecz.f fclose.f pvvcpl.f svfdcf.f mc2scv.f sf2vgc.f   \
   pvccf.f dplm.f pmm.f fnamer.f emmult.f dpmm.f          \
   vobmar.f indfun.f asvdr.f shmplg.f amsdea.f gfdcfd.f   \
   matop.f amlica.f pmm1.f amdlt.f svrint.f fftrlv.f      \
   shdplg.f nmlica.f dpmm1.f plm.f ldgnmf.f sqrll1.f 
#
PAR_O2IBTCTSC2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f svfdcf.f fdcmbd.f     \
   iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f schnla.f    \
   avbmbr.f rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f asvcpl.f  \
   svfwt.f fclose.f pvvcpl.f vecop.f nsvhst.f nsvbta.f    \
   fnamer.f ldgnmf.f gfdcfd.f matop.f amlica.f amsdea.f   \
   amdlt.f vobmar.f nmlica.f asvdr.f dvecz.f fftrlv.f     \
   matind.f bmrcop.f powtwo.f emmult.f pmm.f pmm1.f       \
   plm.f dpmm.f dpmm1.f dplm.f indfun.f vobmb2.f          \
   shkeer.f svrint.f sqrll1.f dl.f bihfrd.f
#
PAR_O2UBCDTS2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f svfdcf.f fdcmbd.f     \
   iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f schnla.f    \
   avbmbr.f rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f asvcpl.f  \
   svfwt.f fclose.f pvvcpl.f vecop.f nsvhst.f nsvbta.f    \
   fnamer.f ldgnmf.f gfdcfd.f matop.f amlica.f amsdea.f   \
   amdlt.f vobmar.f nmlica.f asvdr.f dvecz.f fftrlv.f     \
   matind.f bmrcop.f powtwo.f emmult.f pmm.f pmm1.f       \
   plm.f dpmm.f dpmm1.f dplm.f indfun.f vobmb2.f
#
PAR_O2UBTCTSC2_SOURCES= \
   fopen.f hmfrd.f svfrd.f xarrrd.f svfdcf.f fdcmbd.f     \
   iiasce.f mc2scv.f pvccf.f nphpf.f gauwts.f schnla.f    \
   avbmbr.f rsdv2c.f sf2vgc.f sf2sdc.f xsvsdc.f asvcpl.f  \
   svfwt.f fclose.f pvvcpl.f vecop.f nsvhst.f nsvbta.f    \
   fnamer.f ldgnmf.f gfdcfd.f matop.f amlica.f amsdea.f   \
   amdlt.f vobmar.f nmlica.f asvdr.f dvecz.f fftrlv.f     \
   matind.f bmrcop.f powtwo.f emmult.f pmm.f pmm1.f       \
   plm.f dpmm.f dpmm1.f dplm.f indfun.f vobmb2.f          \
   shkeer.f rtpfce.f shmplg.f svrint.f shdplg.f sqrll1.f
#
PGPLOT_SOURCES= \
   xarrrd.f schnla.f bihfrd.f rcldr.f shmplg.f linerd.f   \
   svfrd.f klm.f rmatop.f svrint.f shdplg.f dplm.f        \
   pmm.f dpmm.f indfun.f gfdcfd.f pmm1.f dpmm1.f          \
   plm.f gfdcfd.f matop.f fopen.f fclose.f fnamer.f       \
   earcmc.f earmir.f rcldr2.f shsfrd.f shc2pt.f lmfind.f
#
PROGDEPLIST_SOURCES= \
   fnamer.f npudfs.f cntric.f fopen.f fclose.f
#
RSVFG_SOURCES= \
   esnaas.f zcpaas.f hminda.f shvecf.f hmfwt.f xarrwt.f   \
   svfwt.f fopen.f fclose.f smitsl.f pmfabf.f fnamer.f    \
   mnewtr.f pvnsrf.f tvsfrf.f pvsfrf.f pmfirf.f chorch.f  \
   chorcf.f chorsf.f pmfsef.f indfun.f
#
SBRLINONSD_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f vecop.f svfdcf.f iocrbd.f hmfwt.f    \
   svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f ldgnmf.f   \
   gfdcfd.f avmato.f sbrrfc.f sbrvmr.f vmeps.f evalas.f   \
   evecex.f radvlf.f matop.f amlp.f  amlc.f  amccfo.f     \
   amta.f  amcl.f  amhst.f iv0gto.f ivgt0o.f iv0cvo.f     \
   ivcv0o.f bmrcop.f amsdea.f dvecz.f asvta.f asvcl.f     \
   vesr.f  asvcpl.f amdlt.f amlica.f amccft.f corcoo.f    \
   amhsar.f invgtt.f shveco.f vfdp.f  forsso.f innlca.f   \
   invcvt.f vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f     \
   cubeop.f fftrlv.f powtwo.f pmm.f   pmm1.f  plm.f       \
   dpmm.f  dpmm1.f dplm.f  emmult.f dl.f    sqrll1.f      \
   indfun.f indshc.f
#
SBRLINONS1_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   sbrvmr.f vthmsr.f cindsw.f vecop.f svfdcf.f iocrbo.f   \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   ldgnmf.f gfdcfd.f avmato.f sbrrfc.f vmeps.f evalas.f   \
   evecex.f radvlf.f matop.f amlp.f  amlc.f  amccfo.f     \
   amta.f  amcl.f  amhst.f iv0gto.f ivgt0o.f iv0cvo.f     \
   ivcv0o.f bmrcop.f amsdea.f dvecz.f asvta.f asvcl.f     \
   vesr.f  asvcpl.f amdlt.f amlica.f amccft.f corcoo.f    \
   amhsar.f invgtt.f shveco.f vfdp.f  forsso.f innlca.f   \
   invcvt.f vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f     \
   cubeop.f fftrlv.f powtwo.f pmm.f   pmm1.f  plm.f       \
   dpmm.f  dpmm1.f dplm.f  emmult.f dl.f    sqrll1.f      \
   indfun.f indshc.f
#
SHEARVFORM_SOURCES= \
   esnaas.f zcpaas.f ontppf.f gauwts.f schnla.f zvnff.f   \
   asfgr.f xarrwt.f hmfwt.f svfwt.f vf2qst.f fopen.f      \
   fclose.f matop.f dvecz.f fftrlv.f fnamer.f powtwo.f    \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   zvdf.f  sqrll1.f indfun.f indshc.f
#
SHVELCRF2V2O_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f zvnff.f asfgr.f svfdcf.f iocrbo.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f avmato.f sbrrfc.f vmeps.f   \
   evalas.f evecex.f radvlf.f matop.f dvecz.f fftrlv.f    \
   amlp.f  amlc.f  amccfo.f amta.f  amcl.f  amhst.f       \
   iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f bmrcop.f   \
   amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f powtwo.f     \
   amdlt.f amlica.f amccft.f corcoo.f amhsar.f invgtt.f   \
   shveco.f vfdp.f  forsso.f innlca.f invcvt.f vfcp.f     \
   vf2qso.f asvdr.f matind.f vfcor.f cubeop.f pmm.f       \
   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f zvdf.f          \
   sqrll1.f emmult.f dl.f indfun.f indshc.f
#
SHVELCRF2V2OD_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f zvnff.f asfgr.f svfdcf.f iocrbd.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f avmato.f sbrrfc.f sbrvmr.f  \
   vmeps.f evalas.f evecex.f radvlf.f matop.f dvecz.f     \
   fftrlv.f amlp.f  amlc.f  amccfo.f amta.f  amcl.f       \
   amhst.f iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f    \
   bmrcop.f amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f     \
   powtwo.f amdlt.f amlica.f amccft.f corcoo.f amhsar.f   \
   invgtt.f shveco.f vfdp.f  forsso.f innlca.f invcvt.f   \
   vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f cubeop.f     \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   zvdf.f  sqrll1.f emmult.f dl.f  indfun.f indshc.f
#
SHVELCRF2V2OS_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f zvnff.f asfgr.f svfdcf.f iocrbo.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f sbrvmr.f fclose.f    \
   fnamer.f vf2qst.f ldgnmf.f gfdcfd.f avmato.f sbrrfc.f  \
   vmeps.f evalas.f evecex.f radvlf.f matop.f dvecz.f     \
   fftrlv.f amlp.f  amlc.f  amccfo.f amta.f  amcl.f       \
   amhst.f iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f    \
   bmrcop.f amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f     \
   powtwo.f amdlt.f amlica.f amccft.f corcoo.f amhsar.f   \
   invgtt.f shveco.f vfdp.f  forsso.f innlca.f invcvt.f   \
   vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f cubeop.f     \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   zvdf.f  sqrll1.f emmult.f dl.f    indfun.f indshc.f
#
SHVELREYNF2V2O_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f zvnff.f asfgr.f svfdcf.f sicrbo.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f avmato.f sbrrfc.f vmeps.f   \
   evalas.f evecex.f radvlf.f matop.f dvecz.f fftrlv.f    \
   amlp.f  amlc.f  amccfo.f amta.f  amcl.f  amhst.f       \
   iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f bmrcop.f   \
   amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f powtwo.f     \
   amdlt.f amlica.f amccft.f corcoo.f amhsar.f invgtt.f   \
   shveco.f vfdp.f  forsso.f innlca.f invcvt.f vfcp.f     \
   vf2qso.f asvdr.f matind.f vfcor.f cubeop.f pmm.f       \
   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f  zvdf.f         \
   sqrll1.f emmult.f dl.f    indfun.f indshc.f
#
SHVELREYNF2V2OD_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f zvnff.f asfgr.f svfdcf.f sicrbd.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f sbrvmr.f avmato.f sbrrfc.f  \
   vmeps.f evalas.f evecex.f radvlf.f matop.f dvecz.f     \
   fftrlv.f amlp.f  amlc.f  amccfo.f amta.f  amcl.f       \
   amhst.f iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f    \
   bmrcop.f amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f     \
   powtwo.f amdlt.f amlica.f amccft.f corcoo.f amhsar.f   \
   invgtt.f shveco.f vfdp.f  forsso.f innlca.f invcvt.f   \
   vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f cubeop.f     \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   zvdf.f  sqrll1.f emmult.f dl.f    indfun.f indshc.f
#
SHVELREYNF2V2OS_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   vthmsr.f cindsw.f zvnff.f asfgr.f svfdcf.f sicrbs.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f sbrvmr.f avmato.f sbrrfc.f  \
   vmeps.f evalas.f evecex.f radvlf.f matop.f dvecz.f     \
   fftrlv.f amlp.f  amlc.f  amccfo.f amta.f  amcl.f       \
   amhst.f iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f    \
   bmrcop.f amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f     \
   powtwo.f amdlt.f amlica.f amccft.f corcoo.f amhsar.f   \
   invgtt.f shveco.f vfdp.f  forsso.f innlca.f invcvt.f   \
   vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f cubeop.f     \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   zvdf.f  sqrll1.f emmult.f dl.f  indfun.f indshc.f
#
SVENSPEC_SOURCES= \
   vecop.f matop.f hmfrd.f xarrrd.f svfrd.f svfdcf.f      \
   shkeer.f fopen.f fclose.f ldgnmf.f gfdcfd.f asvdr.f    \
   fnamer.f emmult.f sqrll1.f indshc.f indfun.f
#
SVPNSMAP_SOURCES= \
   hmfrd.f svfrd.f xarrrd.f hminda.f esnaas.f zcpaas.f    \
   svrint.f hmfwt.f xarrwt.f svfwt.f fopen.f fclose.f     \
   gfdcfd.f fnamer.f matop.f indfun.f
#
VESVCRNFV2O_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   asfgr.f vohmsr.f cindsw.f zvnff.f svfdcf.f sicrbo.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f avmato.f sbrrfc.f vmeps.f   \
   evalas.f evecex.f radvlf.f matop.f dvecz.f fftrlv.f    \
   amlp.f  amlc.f  amccfo.f amta.f  amcl.f  amhst.f       \
   iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f bmrcop.f   \
   amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f powtwo.f     \
   amdlt.f amlica.f amccft.f corcoo.f amhsar.f invgtt.f   \
   shveco.f vfdp.f  forsso.f innlca.f invcvt.f vfcp.f     \
   vf2qso.f asvdr.f matind.f vfcor.f cubeop.f pmm.f       \
   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f  sqrll1.f       \
   zvdf.f  emmult.f dl.f    indfun.f indshc.f
#
VESVCRNFV2OD_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   asfgr.f vohmsr.f cindsw.f zvnff.f svfdcf.f sicrbd.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f sbrvmr.f avmato.f sbrrfc.f  \
   vmeps.f evalas.f evecex.f radvlf.f matop.f dvecz.f     \
   fftrlv.f amlp.f  amlc.f  amccfo.f amta.f  amcl.f       \
   amhst.f iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f    \
   bmrcop.f amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f     \
   powtwo.f amdlt.f amlica.f amccft.f corcoo.f amhsar.f   \
   invgtt.f shveco.f vfdp.f  forsso.f innlca.f invcvt.f   \
   vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f cubeop.f     \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   sqrll1.f zvdf.f  emmult.f dl.f    indfun.f indshc.f
#
VESVCRNFV2OS_SOURCES= \
   fopen.f esnaas.f zcpaas.f nphpf.f gauwts.f schnla.f    \
   asfgr.f vohmsr.f cindsw.f zvnff.f svfdcf.f sicrbs.f    \
   hmfwt.f svfwt.f xarrwt.f svprnt.f fclose.f fnamer.f    \
   vf2qst.f ldgnmf.f gfdcfd.f sbrvmr.f avmato.f sbrrfc.f  \
   vmeps.f evalas.f evecex.f radvlf.f matop.f dvecz.f     \
   fftrlv.f amlp.f  amlc.f  amccfo.f amta.f  amcl.f       \
   amhst.f iv0gto.f ivgt0o.f iv0cvo.f ivcv0o.f vecop.f    \
   bmrcop.f amsdea.f asvta.f asvcl.f vesr.f  asvcpl.f     \
   powtwo.f amdlt.f amlica.f amccft.f corcoo.f amhsar.f   \
   invgtt.f shveco.f vfdp.f  forsso.f innlca.f invcvt.f   \
   vfcp.f  vf2qso.f asvdr.f matind.f vfcor.f cubeop.f     \
   pmm.f   pmm1.f  plm.f   dpmm.f  dpmm1.f dplm.f         \
   sqrll1.f zvdf.f  emmult.f dl.f    indfun.f indshc.f
#
SOURCES= \
        $(CICM2OCDISPLAY_SOURCES)           \
        $(ALLSOURCECODE)  
#
OPTIM=	-O3
SGLIB=  ../lib/subslib.a
FORTRAN= gfortran
.PRECIOUS: 	$(SGLIB)
#
$(SGLIB):	$(SOURCES)
	$(FORTRAN) $(OPTIM) $? -c
	ar rv $(SGLIB) *.o
	ranlib $(SGLIB)
	chmod 644 $(SGLIB)
	\rm *.o
#
