FORTRAN= gfortran
#-------------------------------------------
shc2itfvf: 	shc2itfvf.f
	$(FORTRAN) -o ./shc2itfvf shc2itfvf.f
	rm -f *.o
#-------------------------------------------
gmshcc: 	gmshcc.f
	$(FORTRAN) -o ./gmshcc gmshcc.f
	rm -f *.o
