#
# Makefile for PROGRAMS directory.
#
OPTIM=   -O3  -fallow-argument-mismatch
FORTRAN= gfortran
#
all:	\
        sbrlinons1
#
sbrlinons1:	sbrlinons1.f
	$(FORTRAN) -o ./sbrlinons1 sbrlinons1.f $(OPTIM)
	\rm -f *.o
#
clean:
	sh clean.sh
#
